# App Starter pipeline 

trigger:
  branches:
    include:
    - master
    exclude:
    - user/*

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: 'Hosted Ubuntu 1604'
    steps:    
    - task: Docker@2
      inputs:
        containerRegistry: 'aksregistry'
        repository: 'msgprocessor'
        command: 'buildAndPush'
        Dockerfile: 'src/Dockerfile'
        buildContext: 'src/'
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: 'src/msgprocessor' 
        artifactName: 'helmchart'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: test
    pool:
      name: 'Hosted Ubuntu 1604'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'helmchart'
              downloadPath: '$(System.ArtifactsDirectory)/charts/msgprocessor' 

          - task: AzureCLI@1
            displayName: Deploy App to the Cluster
            inputs:
              # Change here if you changed name for Service Connection
              azureSubscription: 'serviceprincipal'
              scriptLocation: 'inlineScript'
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials -n $(AKS_CLUSTER_NAME) -g $(AKS_CLUSTER_RG)

                ehconnstring=`az eventhubs namespace authorization-rule keys list -n RootManageSharedAccessKey --namespace-name $(EH_NS_NAME) -g $(EH_NS_RG) | jq -r .primaryConnectionString`
                stgconnstring=`az storage account show-connection-string -n $(STG_NAME) -g $(EH_NS_RG) | jq -r .connectionString`
                
                helm upgrade msgprocessor charts/msgprocessor --install \
                  --set image.repository=jetiba.azurecr.io/msgprocessor \
                  --set image.tag=$(Build.BuildId) \
                  --set secrets.ehconnstring=$ehconnstring \
                  --set secrets.ehname=$(EH_NAME) \
                  --set secrets.stgcontainername=$(STG_CONTAINER_NAME) \
                  --set secrets.stgconnstring=$stgconnstring \
                  --namespace arch-aks-sb-dotnet
              workingDirectory: '$(System.ArtifactsDirectory)'